image: barichello/godot-ci:3.1.1

variables:
  EXPORT_NAME: NuttySpace

stages:
  - export
  - deploy

before_script:
  - mkdir -v -p build/linux
  - mkdir -v -p build/windows
  - mkdir -v -p build/mac
  - mkdir -v -p build/web

linux:
  stage: export
  script:
    - godot -v --export "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

windows:
  stage: export
  script:
    - godot -v --export "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows

mac:
  stage: export
  script:
    - godot -v --export "Mac OSX" ./build/mac/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/mac

web:
  stage: export
  script:
    - godot -v --export "HTML5" ./build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web

# Use project root to deploy for the gh-pages branch
deploy-github-pages:
  stage: deploy
  dependencies:
    - web
  script:
    - git checkout gh-pages
    - rm -f *.md
    - mv build/web/** .
    - git config user.email $GIT_AUTHOR_EMAIL
    - git config user.name $GIT_AUTHOR_NAME
    - git add -A
    - 'git commit -m "ci: Deploy GitHub Page $EXPORT_NAME-$CI_JOB_NAME$" -m "Deploy from GitLab pipeline \#$CI_PIPELINE_ID"'
    - git remote add github "$GIT_URL"
    - git push github gh-pages

pages:
  stage: deploy
  dependencies:
    - web
  script:
    - mv build/web/** ./public/
  artifacts:
    paths:
    - public
  only:
    - master
